<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <Platforms>AnyCPU;x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.12.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.32" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.32" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.250610002-experimental3" />
    <PackageReference Include="PaddleOCRSharp" Version="5.0.0.1" />
    <PackageReference Include="Selenium.WebDriver" Version="4.31.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommonTools\CommonTools.csproj" />
    <ProjectReference Include="..\HttpManager\HttpManager.csproj" />
    <ProjectReference Include="..\OcrApi\OcrApi.csproj" />
  </ItemGroup>
  <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.Runtime.Loader.UseRidGraph" Value="true" />
  </ItemGroup>
</Project>
